version: '3.9'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: ./web/.env
    environment:
      DEBUG: 'true'
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      DB_HOST: postgres
      DB_NAME: book_shop_db
      DB_USER: bookshop_admin
      DB_PASS: '0327'
      DB_PORT: 5432
    depends_on:
      - postgres
    command: /usr/local/bin/gunicorn book_shop.wsgi:application -w 2 -b :8000  --reload
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      POSTGRES_DB: book_shop_db
      POSTGRES_USER: bookshop_admin
      POSTGRES_PASSWORD: 0327

volumes:
  web-django:
  web-static:
  pgdata:
