# Generated by Django 4.1.5 on 2023-02-07 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_book_price"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="book",
        ),
        migrations.AlterField(
            model_name="order",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.therestofthebook",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
