# Generated by Django 4.1.5 on 2023-02-14 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 14, 7, 21, 27, 911148, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "New"),
                    ("2", "Approved"),
                    ("3", "Delivery"),
                    ("4", "Done"),
                    ("5", "Canceled"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_detail",
                to="orders.order",
            ),
        ),
    ]
