# Generated by Django 4.1.5 on 2023-02-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderdetail_book_alter_order_book_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_time_and_data",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
