# Generated by Django 4.1.5 on 2023-02-08 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_book_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0005_remove_order_user_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="book",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="book_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.therestofthebook",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
