# Generated by Django 4.1.5 on 2023-02-08 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_book_remove_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="total_price",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
