# Generated by Django 4.1.5 on 2023-02-08 13:12

import django.core.validators
from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_orderdetail_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="total_price",
            field=models.IntegerField(
                default=orders.models.OrderDetail.get_total_price,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
