# Generated by Django 4.1.5 on 2023-02-08 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_orderdetail_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="total_price",
            field=models.IntegerField(
                default=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
