# Generated by Django 4.1.5 on 2023-01-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
