# Generated by Django 4.1.5 on 2023-01-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_bookinstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Enter a city", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="Amount of books in order")),
                ("price", models.IntegerField(help_text="Write your price here")),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a publisher's name", max_length=200
                    ),
                ),
                ("phone", models.IntegerField(help_text="Publisher's phone")),
                (
                    "email",
                    models.EmailField(help_text="Publisher's email", max_length=254),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.city",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.IntegerField(default=1, help_text="Write your price here"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(
                default=1, help_text="Number of books in the store"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BookInstance",
        ),
        migrations.AddField(
            model_name="orders_detail",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.book",
            ),
        ),
    ]
