# Generated by Django 4.1.5 on 2023-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_city_orders_orders_detail_publisher_book_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="phone",
            field=models.CharField(help_text="Publisher's phone", max_length=25),
        ),
    ]
