# Generated by Django 4.1.5 on 2023-01-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_publisher_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=17, verbose_name="ISBN"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="phone",
            field=models.CharField(help_text="Publisher's phone", max_length=30),
        ),
    ]
