# Generated by Django 4.1.5 on 2023-01-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_book_isbn_alter_publisher_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="number_of_pages",
            field=models.IntegerField(default=0, help_text="Number_of_pages"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.publisher",
            ),
        ),
    ]
