# Generated by Django 4.1.5 on 2023-02-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_rename_orders_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="year",
        ),
    ]
