# Generated by Django 4.1.5 on 2023-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_book_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(help_text="Enter a year here", null=True),
        ),
    ]
