# Generated by Django 4.1.5 on 2023-02-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_book_year"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Order_detail",
        ),
    ]
