# Generated by Django 4.1.5 on 2023-02-05 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_delete_order_delete_order_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="quantity",
        ),
        migrations.CreateModel(
            name="BookInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this particular book across whole library",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imprint", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.IntegerField(help_text="Number of books in the store"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Available"), ("n", "Not available")],
                        default="m",
                        help_text="Book availability",
                        max_length=1,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.book",
                    ),
                ),
            ],
        ),
    ]
