# Generated by Django 4.1.5 on 2023-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_book_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="user",
        ),
    ]
